namespace Nebx.Labs.AspNetCore.Responses;

/// <summary>
/// Represents a standardized error response compliant with RFC 7807 (Problem Details for HTTP APIs),
/// extended with application-specific fields such as <see cref="ErrorCode"/>, <see cref="TraceId"/>,
/// and <see cref="Errors"/>.
/// </summary>
public record ErrorResponse
{
    private ErrorResponse()
    {
    }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// This value should be consistent for all occurrences of this problem type.
    /// </summary>
    public string Title { get; private set; } = string.Empty;

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int Status { get; private set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string Detail { get; private set; } = string.Empty;

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// Typically set to the request path.
    /// </summary>
    public string Instance { get; private set; } = string.Empty;

    /// <summary>
    /// An optional application-specific code identifying the error type.
    /// </summary>
    public string? ErrorCode { get; private set; }

    /// <summary>
    /// A collection of field-level validation messages, where each key represents a field name
    /// and the associated value contains an array of validation issues.
    /// </summary>
    public IReadOnlyDictionary<string, string[]>? Errors { get; private set; }

    /// <summary>
    /// The unique trace identifier associated with the request, useful for distributed tracing.
    /// </summary>
    public string TraceId { get; private set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Factory method to create a new <see cref="ErrorResponse"/> instance.
    /// </summary>
    /// <param name="status">The HTTP status code (must be 100–599).</param>
    /// <param name="title">A short, human-readable summary of the problem type.</param>
    /// <param name="detail">A detailed explanation specific to this occurrence of the problem.</param>
    /// <returns>A configured <see cref="ErrorResponse"/> instance.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="status"/> is invalid.</exception>
    /// <exception cref="ArgumentException">Thrown when <paramref name="title"/> is null or empty.</exception>
    /// /// <exception cref="ArgumentException">Thrown when <paramref name="detail"/> is null or empty.</exception>
    public static ErrorResponse Create(int status, string title, string detail)
    {
        if (status is < 100 or > 599)
            throw new ArgumentOutOfRangeException(nameof(status),
                $"Invalid HTTP status code: {status}. Must be between 100 and 599.");

        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title cannot be null, empty, or whitespace.", nameof(title));

        if (string.IsNullOrWhiteSpace(detail))
            throw new ArgumentException("Detail cannot be null, empty, or whitespace.", nameof(title));

        return new ErrorResponse
        {
            Status = status,
            Title = title,
            Detail = detail
        };
    }

    /// <summary>
    /// Sets the trace identifier for this error response.
    /// </summary>
    /// <param name="traceId">The request or operation trace ID.</param>
    public void AddTraceId(string traceId) => TraceId = traceId.ToUpperInvariant();

    /// <summary>
    /// Sets the instance URI identifying where the error occurred.
    /// </summary>
    /// <param name="instance">The request path or resource URI.</param>
    public void AddInstance(string instance) => Instance = instance;

    /// <summary>
    /// Sets the <see cref="ErrorCode"/> to the specified application-defined value.
    /// </summary>
    /// <param name="errorCode">The application-specific identifier representing the error type.</param>
    public void AddErrorCode(string errorCode)
    {
        if (string.IsNullOrWhiteSpace(errorCode))
            throw new ArgumentException("Error code cannot be null, empty, or whitespace.", nameof(errorCode));

        ErrorCode = errorCode.ToUpperInvariant();
    }

    /// <summary>
    /// Replaces the current <see cref="Errors"/> dictionary with the specified collection of error messages.
    /// Typically used to associate validation messages with specific fields or properties.
    /// </summary>
    /// <param name="errors">A dictionary containing field names and corresponding error messages.</param>
    public void AddErrors(IReadOnlyDictionary<string, string[]> errors)
    {
        if (errors == null || errors.Count == 0)
            throw new ArgumentException("The provided error collection cannot be null or empty.", nameof(errors));

        Errors = errors;
    }
}
